### ISSUE TITLE
Report the error when compiling with oneapi and anaconda3.

### ISSUE THREAD

**Issue by ChenqiangHua** [pyatb/pyatb#1]
Dear, 
I try to compile pyatb with ' python setup.py  install ' ,  then error occurs.   Does this means  i  have to change the compiler?

thx a lot!

icpc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /beegfs/home/b00004/anaconda3/include -I/beegfs/home/b00004/anaconda3/include -fPIC -O2 -isystem /beegfs/home/b00004/anaconda3/include -O2 -std=c++11 -fPIC -Wall -shared -fPIC -I/opt/intel/oneapi/mkl/2022.0.2/include/ -I/usr/local/include/eigen3/ -Isrc/cpp/core -Isrc/cpp/interface_python -I/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/pybind11/include -I/beegfs/home/b00004/anaconda3/include/python3.9 -c src/cpp/core/band_structure_solver.cpp -o build/temp.linux-x86_64-3.9/src/cpp/core/band_structure_solver.o -fvisibility=hidden -g0 -qopenmp
icpc: command line warning #10148: option '-Wno-unused-result' not supported
In file included from src/cpp/core/tools.h(5),
                 from src/cpp/core/base_data.h(6),
                 from src/cpp/core/band_structure_solver.h(5),
                 from src/cpp/core/band_structure_solver.cpp(1):
src/cpp/core/use_eigen.h(6): catastrophic error: cannot open source file "Eigen/Eigen"
  #include <Eigen/Eigen>
                        ^

compilation aborted for src/cpp/core/band_structure_solver.cpp (code 4)
error: command '/beegfs/science-share/wannier90_calc/oneapi/compiler/2022.0.2/linux/bin/intel64/icpc' failed with exit code 4

**Comment by pyatb** [comment]
It's possible that you don't have the Eigen library in your environment. You can download the Eigen library from https://eigen.tuxfamily.org/index.php?title=Main_Page. The Eigen library is a header-only library, so it doesn't need to be installed. You can specify the location of the Eigen library in `siteconfig.py`. For more detailed installation instructions, please refer to https://pyatb.github.io/pyatb/installation.html#install.

**Comment by pyatb** [comment]
The folder address where you extracted the Eigen library is the address that needs to be specified in `siteconfig.py`
