### ISSUE TITLE
A bad band structure 

### ISSUE THREAD

**Issue by y1ding** [pyatb/pyatb#1]
Pyatb developers, I found the following situation:
I try to use the pyatb to plot the bands, but I can get a graph like this.
[band.pdf](https://github.com/pyatb/pyatb/files/11362604/band.pdf)

I think something may be wrong. The right band from the abacus should be looked like this.
[Graph1.pdf](https://github.com/pyatb/pyatb/files/11362605/Graph1.pdf)

I wonder whether there are some parameters can be adjusted for this case?
Attachments are ABACUS and PYATB files. (I use ABACUS 3.2.1 and PYATB 1.0.0)

[upload.zip](https://github.com/pyatb/pyatb/files/11362606/upload.zip)

Thanks

**Comment by jingan-181** [comment]
I used the input files you provided me with for abacus and pyatb to calculate, but I couldn't replicate the issue you raised. 
The band structure obtained from pyatb calculations is consistent with the result in Graph1.pdf. 

I used version v3.2.0 of abacus and v1.0.0 of pyatb, and none of the input files were modified. 

However, I noticed that our data-HR-sparse_SPIN0.csr and data-SR-sparse_SPIN0.csr are different, possibly indicating an error in the HR and SR outputs from abacus. 

Can you please provide more details?

Here are my results:
[upload_test.zip](https://github.com/pyatb/pyatb/files/11398934/upload_test.zip)

**Comment by y1ding** [comment]
Thanks for your help.
However, after try the different abacus (3.2.0, 3.2.1 and 3.2.2), I still fall into the same problems.
I suspect my installed pyatb may be some problem. Even I use the your csr files, I still get the bad band strucutures. (Only for the atom number becomes more, I have checked the eamples and provided a graphene test, I have get the right band structures)

**Comment by y1ding** [comment]
Attenment are the my pyatb files : One is the graphene_pass_OK, which give the right band, One is the bad case, which use your csr files.

**Comment by y1ding** [comment]
[Ding.zip](https://github.com/pyatb/pyatb/files/11403023/Ding.zip)

**Comment by y1ding** [comment]
I use following settings to install the pyatb:  python3.9 , mkl2018   CXX = "icpc"
LAPACK_DIR = "/public/software/intel/2018.4/compilers_and_libraries/linux/mkl"   
icpc -V
Intel(R) C++ Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.5.0 Build 20211109_000000
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.

**Comment by y1ding** [comment]
Thanks for the suggestions of Jingan。 After try several icpc and mkl，I use both the 2021 version can solve such problem.
