### ISSUE TITLE
FileExistsError: [Errno 17] File exists: '/data/unfolding/hse_cp/pyatb/Out'

### ISSUE THREAD

**Issue by Luc1anoo** [pyatb/pyatb#2]
I encountered some problem during using ABACUS with pyatb package . I put the details in the following Bohrium Notebook :
https://bohrium.dp.tech/notebook/0259289858174d53bdaa50c111f31edc  #Qs_pyatb.ipynb

**Comment by pyatb** [comment]
I have given a corresponding reply on the website you provided. If you have not solved your problem, you can leave your contact information (email or the like).

**Comment by pyatb** [comment]
Q1: 
1. I have never encountered a problem similar to File. If possible, please upload your error example. 
2. The energy band diagram you give should not be an unfolding diagram, it should be calculated by `BAND_STRUCTURE`.
3. When using `BANDUNFOLDING`, you need to provide additional structure files and orbital files (similar to *.orb files). In your error message, it is mentioned that "Ge_gga_8au_100Ry_2s2p2d.orb" was not found.
4. You can try the examples under examples/NV/supercell/ first.

Q2: Using the `BANDUNFOLDING` function, "spectral_weight.dat" will be generated in Out/Bandunfolding after successful operation. The second column of data in this file represents the weight of each band at each k point.

Q3: PYATB draws a color map, similar to the ARPES spectrum. In a colormap, points with small weights will be masked in the background. In principle, no trade-offs should be made to any data point.

Q4: In ABACUS, if the INPUT file sets `dft_functional hse`, the hybrid functional can be used. For the adjustment parameters related to the hybrid functional, please refer to the ABACUS official manual.

**Comment by Luc1anoo** [comment]
Maybe my pyatb somehow didn't work at all from the beginning... I added the entire process of installation at the bottom of Notebook, pls check out. Thx.

**Comment by Luc1anoo** [comment]
The problems have been solved by reinstalling mpi. Great thanks to the help!
