### ISSUE TITLE
How to output velocity matrix in pyatb

### ISSUE THREAD

**Issue by DzzZ1** [pyatb/pyatb#22]
Hello developer, I want to get the output file of the velocity matrix. 
I learned that pyatb can calculate the velocity matrix. The velocity matrix is ​​mentioned in the calculations of the Optical Conductivity module(https://bohrium.dp.tech/notebooks/35791425971)
I think the corresponding part of velocity matrix should be in velocity_solver.cpp. I tried to modify this file, but due to my unfamiliarity with C++, even if I modified the code, it still failed.  Could you tell me how to get the velocity matrix, thank you very much.

**Comment by jingan-181** [comment]
You can directly use `import pyatb` to build custom computational functionalities by creating tight-binding model. The basic APIs currently provided by pyatb can be found in `src/pyatb/tb/solver.py`. Below is an example of calculating the velocity matrix at arbitrary k-points.

[tb_velocity.zip](https://github.com/user-attachments/files/17842302/tb_velocity.zip)

**Comment by DzzZ1** [comment]
Thanks for your help, I have got it.
